name: amlexperimentationexamples
dependencies:
- python=3.6.10
- pip=20.0.2
- pip:
  - numpy==1.15.4
  - pandas==1.0.3
  - scikit-learn==0.20.1
  - scipy==1.0.0
  - matplotlib==3.0.2
  - utils==0.9.0
  - setuptools
  # Required packages for AzureML execution, history, and data preparation.
  - azureml-sdk[automl]==1.3.0
  - azureml-defaults==1.3.0
  - azure-cli==2.0.58